### PR TITLE
Add query by mapIds api

### PR DESCRIPTION
**Pull request by ktKongTong**
resolve: https://github.com/beatmaps-io/beatsaver-main/issues/202

### CODE REVIEW

**Comment by Top-Cat** [comment]
This should not be a post. See maps by hash

**Comment by ktKongTong** [comment]
> This should not be a post. Nor should it be unrestricted. See maps by hash

thanks. already changed

**Comment by Top-Cat** [comment]
test this please

**Comment by Top-Cat** [comment]
test this please

**Pull request merged**
